name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}  # Use your secret here

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/asish1346/blum:latest
          docker push ghcr.io/asish1346/blum:latest
